const express = require("express");
const categories = require("../routes/categories");
const tags = require("../routes/tags");
const subcategories = require("../routes/subcategories");
const customers = require("../routes/customers");
const shops = require("../routes/shops");
const products = require("../routes/products");
const shopProducts = require("../routes/shopProducts");
// const rentals = require("../routes/rentals");
const segments = require("../routes/segments");
const users = require("../routes/users");
const auth = require("../routes/auth");
const order = require("../routes/order");
const error = require("../middleware/error");

module.exports = function (app) {
  app.use(express.json());
  app.use("/api/categories", categories);
  app.use("/api/tags", tags);
  app.use("/api/segments", segments);
  app.use("/api/subcategories", subcategories);
  app.use("/api/customers", customers);
  app.use("/api/shops", shops);
  app.use("/api/products", products);
  app.use("/api/shop-products", shopProducts);
  app.use("/api/orders", order);
  app.use("/api/users", users);
  app.use("/api/auth", auth);
  // app.use("/api/returns", returns);
  app.use(error);
};
